### ISSUE TITLE
Generate a list of potential partners for this project

### ISSUE THREAD

**Issue by tajaran** [Code-For-Chicago/Air-Quality#15]
Identify Chicago based partners who work in smaller areas. Look for environmental justice groups serving at the neighborhood (ideally).

Partner should have the ability to communicate info to these areas.

**Comment by TheeChris** [comment]
I think we can mark this done for now. If can't find a partner from the current list, we can revisit.

**Comment by tajaran** [comment]
Okay sounds good!
