### ISSUE TITLE
Add ReviewNB GitHub app for viewing Jupyter notebook diffs

### ISSUE THREAD

**Issue by notchia** [Code-For-Chicago/Air-Quality#23]
I've found that [the ReviewNB GitHub app](https://github.com/marketplace/review-notebook-app) makes reviewing changes to Juypter notebooks in pull requests way easier. I think someone who has access to the Code-for-Chicago account would need to add it to the [installed GitHub apps](https://github.com/Code-For-Chicago/Air-Quality/settings/installations) for this repo.

**Comment by rahulgoel97** [comment]
Just added it - let me know if you can see it!

**Comment by notchia** [comment]
I see it, thanks! For some reason right now it's not automatically adding the ReviewNB comment to my pull request, but maybe that's because I started the PR prior to you adding the app. Hopefully it'll work on the next one.
