### ISSUE TITLE
Explore correlation between AirNow and PurpleAir PM2.5

### ISSUE THREAD

**Issue by TheeChris** [Code-For-Chicago/Air-Quality#3]
How well is the AirNow data correlated with more localized PurpleAir sensors. Start by comparing an average of the PurpleAir sensors around McKinley park with the Chicago area average from AirNow.

**Comment by TheeChris** [comment]
Compare the pm2.5 measures from AirNow to those of PurpleAire parent and child (B) sensors. You may need to find a way to average over time periods, but worth trying without first.  See if there are seasonal differences between summer and fall.

**Comment by nilaykumar** [comment]
A quick note: changing`figure, axis = plt.subplots(nSensors)` to `figure, axis = plt.subplots(nSensors, sharex = True)` in `plot_seasonal_trends` should fix the time-series plot for 39th and Damen.

**Comment by TheeChris** [comment]
With the completion of the EPA-corrected PurpleAir correlation, I'm calling this one done for now.
