### ISSUE TITLE
Document how to get sensor info for new locations

### ISSUE THREAD

**Issue by rahulgoel97** [Code-For-Chicago/Air-Quality#33]
- Documentation to get key Purple Air API params to expand analysis to different locations.

**Comment by TheeChris** [comment]
[This ](https://github.com/Code-For-Chicago/Air-Quality/blob/main/docs/121521%20Air%20Quality%20Project%20-%20Code%20for%20Chicago.pdf)looks great, Rahul. Thanks for putting it together.
