### ISSUE TITLE
Size # of sensors req'd

### ISSUE THREAD

**Issue by rahulgoel97** [Code-For-Chicago/Air-Quality#34]
Estimate a range of number of sensors required for:

- Ideal coverage of 25%, 50%, 75%, 100% coverage of Chicago population
- Need to understand sensors per capita - look for reports, docs, etc
- 10 year total cost of buying + maintaining sensors

**Comment by TheeChris** [comment]
I'm going to close this issue with the work from Rahul's sizing doc (https://github.com/Code-For-Chicago/Air-Quality/blob/main/docs/011221%20Sensor%20Sizing.xlsx)
